"""Generate the data dictionary from the configuration (so the two cannot drift apart)."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from ..config import REPO_ROOT, ModelConfig


def _fmt(x) -> str:
    if isinstance(x, float):
        return f"{x:.3g}"
    return str(x)


def build(cfg: ModelConfig, out_md: Path | None = None, out_csv: Path | None = None) -> pd.DataFrame:
    df = cfg.registry.table()
    out_md = out_md or REPO_ROOT / "docs" / "data_dictionary.md"
    out_csv = out_csv or REPO_ROOT / "data" / "processed" / "data_dictionary.csv"
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_csv, index=False)

    lines = [
        "# Data dictionary",
        "",
        "_Generated by `scripts/build_data_dictionary.py` from `config/risk_parameters.yaml`. Do not edit by hand._",
        "",
        "Every value is an **assumption for a fictional asset**. `basis` records what kind of assumption:",
        "",
        "| basis | meaning |",
        "|---|---|",
        "| assumption | analyst judgement for this fictional asset |",
        "| order_of_magnitude | placed in the general range reported by the *type* of public source named in the rationale; the number is not taken from that source |",
        "| engineering_convention | a standard modelling choice (e.g. annual proof test, beta-factor range) |",
        "| synthetic_calibrated | generic prior, optionally updated with the synthetic records (Bayesian module) |",
        "",
        "Uncertainty: all parameters below are **epistemic** (sampled once per simulated world). Aleatory variability",
        "(event counts, branch outcomes, per-event durations and costs, year-level drivers, oil price) is described after the table.",
        "",
    ]
    for cat, g in df.groupby(df["category"].str.split("/").str[0], sort=False):
        lines += [f"## {cat.replace('_', ' ').title()}", "",
                  "| variable | definition | unit | distribution | median | 5–95 % | basis | rationale |", "|---|---|---|---|---|---|---|---|"]
        for r in g.itertuples():
            rng = "—" if r.p05 == r.p95 else f"{_fmt(r.p05)} – {_fmt(r.p95)}"
            lines.append(f"| `{r.variable}` | {r.definition} | {r.unit} | {r.distribution} | {_fmt(r.median)} | {rng} | {r.basis} | {r.rationale} |")
        lines.append("")

    al, fin, drv = cfg.aleatory, cfg.financial, cfg.drivers
    lines += [
        "## Aleatory (per-event and per-year) quantities",
        "",
        "| quantity | definition | distribution | source/rationale |",
        "|---|---|---|---|",
        "| event counts | number of events of each source in a year | mixed Poisson: Poisson(λ(θ) × year-driver) | standard frequency model; driver adds year-to-year overdispersion |",
        "| event-tree branch | outcome of each release | categorical from event-tree path probabilities | derived |",
        f"| per-event downtime | platform outage duration | lognormal around the outcome median, log-sd {al['downtime_sigma']} | assumption |",
        f"| per-event damage fraction | fraction of replacement value destroyed | Beta around the outcome mean, a+b = {al['damage_beta_concentration']} | assumption |",
        f"| per-event costs given as medians | repair, damage, ER costs | lognormal, log-sd {al['cost_sigma']} | assumption |",
        f"| year drivers {', '.join(drv['names'])} | weather severity, logistics constraint, integrity condition | lognormal mean 1, sigma {drv['sigma']} | assumption; correlated in Model B |",
        f"| oil price | annual average price | lognormal median {fin['oil_price']['median']} USD/bbl, sigma {fin['oil_price']['sigma']} | assumption, not a forecast |",
        "",
        "## Fixed financial constants",
        "",
        "| constant | value | note |",
        "|---|---|---|",
        f"| logistics_day_rate_usd | {fin['logistics_day_rate_usd']:,.0f} | vessel + helicopter support during repairs (assumption) |",
        f"| restart_cost_usd | {fin['restart_cost_usd']:,.0f} | per platform shutdown (assumption) |",
        f"| evacuation_cost_usd | {fin['evacuation_cost_usd']:,.0f} | full evacuation of the complex (assumption) |",
        f"| weather_demanning_cost_usd | {fin['weather_demanning_cost_usd']:,.0f} | precautionary de-manning (assumption) |",
        f"| env_cost_per_bbl_scenario_usd | {fin['env_cost_per_bbl_scenario_usd']:,.0f} | **scenario assumption only**; 0 = excluded |",
        f"| discount_rate | {fin['discount_rate']} | for annualising mitigation capex (assumption) |",
        "",
        "## Platform attributes (config/asset_config.yaml)",
        "",
        "| platform | name | replacement value (USD) | production (bbl/d) | leak-source factor | gas fraction of releases | P(power lost given fire here) |",
        "|---|---|---|---|---|---|---|",
    ]
    for c, p in cfg.asset["platforms"].items():
        lines.append(f"| {c} | {p['name']} | {p['replacement_value_usd']:,.0f} | {p['production_bopd']:,} | {p['release_equipment_factor']} | "
                     f"{p['gas_release_fraction']} | {p['p_power_loss_given_fire']} |")
    lines.append("")
    out_md.write_text("\n".join(lines), encoding="utf-8")
    return df
